### ISSUE TITLE
Please add "set the type of aliyun.qcow2 as virtio"

### ISSUE THREAD

**Issue by Vidos** [alibaba/cloud-kernel#1]
When I boot the qcow2, the default type is IDE, but it should be virtio, so could you please add that to main page?

**Comment by casparant** [comment]
> When I boot the qcow2, the default type is IDE, but it should be virtio, so could you please add that to main page?

Hi! virtio driver is already built inside in the image, you should set the target driver in your libvirt xml, virt-manager UI or in qemu-kvm command line by yourself. Which emulator and/or GUI tool are you using to boot the qcow2 image, please?

**Comment by Vidos** [comment]
Thanks for quick reply, you may misunderstand.
I have booted it.
Well when I use virt-manager to run this qcow2, the disk type will be set as IDE by default.
So I just suggest you add an explanation on the main page that the disk type is virtio, that will be more user-friendly.
Thanks so much.

**Comment by casparant** [comment]
Ah, I see. Will improve the documentation later. Thanks for the suggestion.

**Comment by casparant** [comment]
Wiki updated. close as fixed.
