### ISSUE TITLE
docker-ce doesn't meet dependency requirements

### ISSUE THREAD

**Issue by whao** [alibaba/cloud-kernel#13]
I met the following dependency issues when upgrading docker today.

```
--> Running transaction check
---> Package docker-ce-rootless-extras.x86_64 0:20.10.0-3.el7 will be installed
--> Processing Dependency: fuse-overlayfs >= 0.7 for package: docker-ce-rootless-extras-20.10.0-3.el7.x86_64
--> Processing Dependency: slirp4netns >= 0.4 for package: docker-ce-rootless-extras-20.10.0-3.el7.x86_64
--> Finished Dependency Resolution
Error: Package: docker-ce-rootless-extras-20.10.0-3.el7.x86_64 (docker-ce-stable)
           Requires: slirp4netns >= 0.4
           Available: slirp4netns-0.3.0-1.1.al7.x86_64 (extras)
               slirp4netns = 0.3.0-1.1.al7
Error: Package: docker-ce-rootless-extras-20.10.0-3.el7.x86_64 (docker-ce-stable)
           Requires: fuse-overlayfs >= 0.7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

It seems that `slirp4netns` does not meet the minimum version requirement (maybe it will be updated soon) and `fuse-overlayfs` is not available (I have enabled the Extra Repo).

My OS info

```
Distributor ID:	AlibabaCloud(AliyunLinux)
Description:	Alibaba Cloud Linux (Aliyun Linux) release 2.1903 LTS (Hunting Beagle) 
Release:	2.1903
Codename:	HuntingBeagle
```

I appreciate for engineers' work.

**Comment by Jacob-jiangbo** [comment]
Thanks for reporting this issue. 

Will fix it soon then let you know!

**Comment by geliwei** [comment]
mirror synced, pls give a try

**Comment by Scarick** [comment]
Hi, I've got the same output on Oracle Linux 7.9

**Comment by whao** [comment]
> mirror synced, pls give a try

@geliwei fixed! Thanks for your help! 🎉

**Comment by rakeshmore2210** [comment]
Error: Package: docker-ce-rootless-extras-20.10.9-3.el7.x86_64 (docker-ce-stable)
           Requires: fuse-overlayfs >= 0.7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
