### ISSUE TITLE
Missing a Dingtalk Group for Ali linux .

### ISSUE THREAD

**Issue by netroby** [alibaba/cloud-kernel#14]
Hi , i am happy to see alibaba anolis os open.
Missing a Dingtalk group for community.

**Comment by casparant** [comment]
Hi, thanks for reporting. Anolis OS would be run by OpenAnolis Commuity, will forward your suggestion to the community. Currently a wechat group is availble for discussions. 
![596E91AE-0C42-4697-9257-2FFCE008510D](https://user-images.githubusercontent.com/60645/103187650-1836bc00-4900-11eb-8ea8-a1ced695dbd8.jpeg)

**Comment by netroby** [comment]
Thanks. i joined it.
