### ISSUE TITLE
`CONFIG_CROSS_MEMORY_ATTACH` is not set in the kubernetes engine

### ISSUE THREAD

**Issue by YangKeao** [alibaba/cloud-kernel#15]
Hi. I'm a developer for [chaos-mesh](https://github.com/chaos-mesh/chaos-mesh), and we're testing `chaos-mesh` on the aliyun Container Kubernetes Service. However, some chaos may fail to work because `CONFIG_CROSS_MEMORY_ATTACH` is not set (I have checked the config through mounting the `boot` volume and read `config-4.19.91-21.al7.x86_64`. ).

```
root@ubuntu:/boot# cat config-4.19.91-21.al7.x86_64 |grep CONFIG_CROSS_MEMORY
# CONFIG_CROSS_MEMORY_ATTACH is not set
root@ubuntu:/boot# 
```

It seems that the compiling config is set `y` for `alios7` (in this [config](https://github.com/alibaba/cloud-kernel/blob/linux-next/configs/kernel-4.19-x86_64-alios7.config)). Why it's not `y` for the Kubernetes engine? Is there any security or other concern?

**Comment by Jacob-jiangbo** [comment]
ck22 already enabled CONFIG_CROSS_MEMORY_ATTACH
(http://mirrors.aliyun.com/alinux/2.1903/plus/x86_64/Packages/kernel-4.19.91-22.al7.x86_64.rpm)

# cat /boot/config-4.19.91-22.al7.x86_64 | grep CONFIG_CROSS_MEMO
CONFIG_CROSS_MEMORY_ATTACH=y

**Comment by YangKeao** [comment]
Thanks :beers:
