### ISSUE TITLE
Alibaba Cloud Linux release 3无wireguard模块么？

### ISSUE THREAD

**Issue by vinsonzou** [alibaba/cloud-kernel#17]
Alibaba Cloud Linux release 3都升级至5.10了，是没内置wireguard模块么？

**Comment by shiloong** [comment]
感谢你的反馈!
是的, 目前发布版本里默认没有配置这个模块.
请问你这边对这个模块是有业务场景需求吗? 
我们会考虑在 Alinux3 下一版本配置成模块形式.

**Comment by vinsonzou** [comment]
建议有可选项，比如对标社区的centos-plus，要不然用户冲着5.10内核来，结果核心的wireguard模块没有。

**Comment by vinsonzou** [comment]
> 感谢你的反馈! 是的, 这个模块是5.6内核才引入特性, 目前Alinux3发行版没有明确的业务场景, 默认就没有开启. 请问你这边对这个模块是有业务场景需求吗? 如果用户对这个模块有需求, 我们会评估在 Alinux3 下一版本配置成模块形式.

业务场景有需要，不知什么时候能配置呢？或者给用户一个操作选项也行。

**Comment by imhun** [comment]
同问，要启用难道只能自己编译内核吗

**Comment by anananyang** [comment]
这个问题需要怎么解决

**Comment by maqiao-mq** [comment]
最新的5.10.134-13版本，已经打开了wireguard配置了。
可以使用以下命令安装该版本：
`yum install kernel-5.10.134-13.al8.x86_64`

**Comment by gopower** [comment]
系统 :Linux cavalry 5.10.134-16.2.al8.x86_64 #1 SMP Mon Mar 4 08:43:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

错误信息:
2024-03-27T02:17:06.951Z Server Listening on http://0.0.0.0:51821
2024-03-27T02:17:06.953Z WireGuard Loading configuration...
2024-03-27T02:17:06.955Z WireGuard Configuration loaded.
2024-03-27T02:17:06.955Z WireGuard Config saving...
2024-03-27T02:17:06.957Z WireGuard Config saved.
$ wg-quick down wg0
$ wg-quick up wg0
Error: Command failed: wg-quick up wg0
[#] 
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 10.8.0.1/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT;
modprobe: can't change directory to '/lib/modules': No such file or directory
modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.10 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
[#] ip link delete dev wg0

    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5) {
  code: 3,
  killed: false,
  signal: null,
  cmd: 'wg-quick up wg0'
}

**Comment by gopower** [comment]
已解决

**Comment by cnlutong** [comment]
> 已解决

哥们请问怎么解决的呢？
