### ISSUE TITLE
Missing yum-plugin-releasever-adapter in Alinux 3 alinux3-plus repo

### ISSUE THREAD

**Issue by whao** [alibaba/cloud-kernel#18]
Hi,

I updated my instance to Alinux 3 and found that the package `yum-plugin-releasever-adapter` is missing in `AliYun.repo` when installing `docker-ce` using Docker official repo. I have searched all repos in `AliYun.repo` including `alinux3-plus` which should be named as `plus` in Aliunx 2.

I am wondering if there is a new way to alter `$releasever` in Docker repo in Aliunx 3 or the package is missing somehow.

I manually changed the repo for now but I am looking forward to having a more decent way :)

Thank you

**Comment by xuchunmei000** [comment]
On Alinux3, the plugin name is dnf-plugin-releasever-adapter

**Comment by whao** [comment]
@xuchunmei000 Thanks a lot for your help!
