### ISSUE TITLE
failed to restrict blkio bps device with backport

### ISSUE THREAD

**Issue by cuericlee** [alibaba/cloud-kernel#2]
I use Alinyun Linux 4.19.57 > 4.19.36 with cgwb_v1 enabled， async IO bps limits does not work. In this case, only direct io works as expected.

**Comment by josephhz** [comment]
Please follow the wiki to configure your cgroups.
https://github.com/alibaba/cloud-kernel/wiki/cgroup-writeback-v1-interface

**Comment by josephhz** [comment]
Hi, when following with the steps described in the wiki, does it work for you?

**Comment by josephhz** [comment]
As discussed, it is because throttling happens on block layer, so we should observe the result from iostat or block cgroup io service bytes instead of foreground process write speed like dd.
